apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: mrakaki
  labels:
    app: database
spec:
  ports:
  - port: 3306
    name: mariadb
  type: ClusterIP
  selector:
    app: database
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: database-config
  namespace: mrakaki
data:
  mariadb.cnf: |
    [server]

    [mariadbd]

    #user                    = mysql
    pid-file                = /run/mysqld/mysqld.pid
    basedir                 = /usr

    #
    # * Fine Tuning
    #

    #key_buffer_size        = 128M
    #max_allowed_packet     = 1G
    #thread_stack           = 192K
    #thread_cache_size      = 8
    # This replaces the startup script and checks MyISAM tables if needed
    # the first time they are touched
    #myisam_recover_options = BACKUP
    #max_connections        = 100
    #table_cache            = 64

    #server-id              = 1
    #log_bin                = /var/log/mysql/mysql-bin.log
    expire_logs_days        = 10
    #max_binlog_size        = 100M
    innodb_buffer_pool_size = 1024M

    [embedded]

    [mariadbd]

    [mariadb-11.5]
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
  namespace: mrakaki
spec:
  selector:
    matchLabels:
      app: database
  serviceName: database
  replicas: 1
  template:
    metadata:
      labels:
        app: database
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mariadb
        image: mariadb
        env:
          - name: MARIADB_RANDOM_ROOT_PASSWORD
            value: "true"
        ports:
        - containerPort: 3306
          name: mariadb
        volumeMounts:
        - name: database
          mountPath: /var/lib/mysql/
        - name: mariadb-config
          mountPath: /etc/mysql/mariadb.conf.d
        resources:
          requests:
            cpu: 750m
            memory: 1.5Gi
          limits:
            cpu: 1000m
            memory: 2Gi
      volumes:
      - name: mariadb-config
        configMap:
          name: database-config
  volumeClaimTemplates:
  - metadata:
      name: database
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "longhorn"
      resources:
        requests:
          storage: 25Gi
