apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication
  namespace: mrakaki
  labels:
    app: authentication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication
  template:
    metadata:
      labels:
        app: authentication
    spec:
      containers:
      - name: authentication
        image: mrakaki/dev-containers:mrakaki-eve-auth.0.0.1
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production
        - name: SPRING_CONFIG_IMPORT
          value: configserver:http://configuration:8888
        ports:
          - name: http
            containerPort: 8080
        resources:
          requests:
            memory: "300Mi"
            cpu: "300m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 2022
          failureThreshold: 5
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 2022
          failureThreshold: 5
          initialDelaySeconds: 30
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: authentication
  namespace: mrakaki
spec:
  type: ClusterIP
  ports:
  - port: 8080
    name: http
  selector:
    app: authentication