apiVersion: apps/v1
kind: Deployment
metadata:
  name: configuration
  namespace: mrakaki
  labels:
    app: configuration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configuration
  template:
    metadata:
      labels:
        app: configuration
    spec:
      containers:
      - name: configuration
        image: mrakaki/dev-containers:mrakaki-eve-config.0.0.2
        ports:
          - name: http
            containerPort: 8888
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 2022
          failureThreshold: 5
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 2022
          failureThreshold: 5
          initialDelaySeconds: 30
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: configuration
  namespace: mrakaki
spec:
  type: ClusterIP
  ports:
  - port: 8888
    name: http
  selector:
    app: configuration