apiVersion: apps/v1
kind: Deployment
metadata:
  name: universe
  namespace: mrakaki
  labels:
    app: universe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: universe
  template:
    metadata:
      labels:
        app: universe
    spec:
      containers:
      - name: universe
        image: mrakaki/dev-containers:mrakaki-eve-universe.0.0.1
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production
        - name: SPRING_CONFIG_IMPORT
          value: configserver:http://configuration:8888
        ports:
          - name: http
            containerPort: 8080
        resources:
          requests:
            memory: "768Mi"
            cpu: "750m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 2022
          failureThreshold: 5
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 2022
          failureThreshold: 5
          initialDelaySeconds: 30
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: universe
  namespace: mrakaki
spec:
  type: ClusterIP
  ports:
  - port: 8080
    name: http
  selector:
    app: universe