apiVersion: batch/v1
kind: CronJob
metadata:
  name: universe-update-orders
  namespace: mrakaki
spec:
  schedule: "15 */4 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: universe
            image: mrakaki/dev-containers:mrakaki-eve-universe.0.0.5
            args:
              - updateOrders
            env:
            - name: SPRING_PROFILES_ACTIVE
              value: production
            - name: SPRING_CONFIG_IMPORT
              value: configserver:http://configuration:8888
            resources:
              requests:
                memory: "768Mi"
                cpu: "750m"
              limits:
                memory: "1Gi"
                cpu: "1000m"
          restartPolicy: OnFailure
