apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
  namespace: mrakaki
  labels:
    app: zipkin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin
  template:
    metadata:
      labels:
        app: zipkin
    spec:
      containers:
      - name: zipkin
        image: openzipkin/zipkin
        ports:
          - name: http
            containerPort: 9411
        resources:
          requests:
            cpu: 50m
            memory: 256Mi
          limits:
            cpu: 250m
            memory: 384Mi
---
apiVersion: v1
kind: Service
metadata:
  name: zipkin
  namespace: mrakaki
spec:
  type: ClusterIP
  ports:
  - port: 9411
    name: http
  selector:
    app: zipkin