apiVersion: v1
kind: Service
metadata:
  name: allianceauth-nginx
  labels:
    app: allianceauth-nginx
spec:
  type: ClusterIP
  selector:
    app: allianceauth-nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
