apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail
spec:
  interval: 10m
  chart:
    spec:
      chart: promtail
      version: "6.*"
      sourceRef:
        kind: HelmRepository
        name: grafana-promtail
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    fullnameOverride: promtail
    serviceMonitor:
      enabled: true
    config:
      clients:
        - url: http://loki.monitoring.svc:3100/loki/api/v1/push
      snippets:
        pipelineStages:
          - cri: {}
