# kubectl -n flux-system create secret generic discord-url \
#   --from-literal=address=https://discord.com/api/webhooks/YOUR/WEBHOOK/URL
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: discord
  namespace: flux-system
spec:
  type: discord
  channel: general
  secretRef:
    name: discord-url