apiVersion: v1
kind: Secret
metadata:
    name: npm-secret
type: Opaque
stringData:
    db-host: ENC[AES256_GCM,data:BBQzXklX8LICInj9BasV8c/UzRqdHcILJp9KY5nNsinmjyM=,iv:HXx6oh2nT2HThkaW44AUr0KvDfiQcqf7NCpsP7+XR4o=,tag:3qMbxSpILM1JDpEupVAQYg==,type:str]
    db-port: ENC[AES256_GCM,data:Dw/uVg==,iv:6BAO1Dt5K2lXLeH12ua+KnHen73zZ/QOV/kSrXtg+TI=,tag:/zimJUZdtJtOJdgVJFaq2w==,type:str]
    db-name: ENC[AES256_GCM,data:V00y,iv:ebMZeOt1R3W5cgxfs1LShLx9BKC8AzJxlFnNlaVEaMs=,tag:jafjN4M2JYhuSsV2EC2rzg==,type:str]
    db-user: ENC[AES256_GCM,data:M4T1,iv:Hlw5gLAMtVCaLjInJX4rugIggSRCsn4Rptbp9EBE4zg=,tag:GORJwepURZHF+dVuSIvLdA==,type:str]
    db-password: ENC[AES256_GCM,data:iuUwaGeQB5HHOU9jBXid,iv:xf2RUdKUKkHo9rlVPdpWuvLuMotKoeMTe3X5j/rz3MA=,tag:AJlXIXyd4pISxSxY37Gj4g==,type:str]
sops:
    age:
        - recipient: age1fqgnfywtrv0v0v05xph328e90fk63vwsmz3qhra8zljdfsqn3fgquup54j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ZDVOV1g0Q2JOZFM0R1Q4
            ZTF4OTd1NDJzelY3QklRMitTVXRHN015Z1ZnCk9DdkgvaG8xM3NueVhSZlIvMTlL
            Q1F1bnl5OGwyL3Q1Y1V2NXVhSkVwU2cKLS0tIGxJa3piaW9DMDFIQTZ1QStkVkpV
            WVZJbStmamJBU0RESzhKL1AwK01icDgKzkDFbUnWKeBpZU7mm3bB1Zmai4hOXjcX
            DkEBunHR4ixFcxbsZr0tKSPgOLz8m83sktmlQjZxfvYP91BHHO9Btg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-13T03:05:22Z"
    mac: ENC[AES256_GCM,data:TziPw5Sqq8eoeQu9b0ICw+tzSDwkynGiylRXEOK99vIq8Tf3QTuzDDFVAYHoe5dfZuWoLL9xjwKbOhBwoMoDN3K3ZTAumN4Ny8ZpRqelgiZrabXdunUV642cPwUMvvd+6L7gkIQ7mE+qB7/C3e0kJJ7soBfhGWI/WfMg2EAnyFE=,iv:n4UK2CfvtO1EqXAZ5PMw5++DCZ3y54XyJCP18O/NbyQ=,tag:S2zkgQ7ll+tjl0YxzvX6hQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
