apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-token
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:UaMvBkhJSGtWh7clncjhtYq/4P+lIc6nO2Lz4l2px8ceMM7iOK/QvvJ45QzDoRaYHL2zMSX4wBr2YSagyay2g14yXhsvzoF+13vG7t9v7ZhJWQYAS4NqzkYZjNWS8pzzPtzhaqZU3Whfkstnag4VX+VEGkqdY8lXqaKrU+1zgo0gPvsQtp/4vcu4xPrTxt4gy4Adnfm+R4mEiEN/fzgYUoZkdBKnxYacUDhkHv6UIqohEulj3ZzJvA==,iv:3bGCI2fI7sEOgo5HzZenLCzN0O/PwYcqV3xhaIv1sNw=,tag:HFY0oeAA9QUKBV58AhJLGQ==,type:str]
sops:
    age:
        - recipient: age1fqgnfywtrv0v0v05xph328e90fk63vwsmz3qhra8zljdfsqn3fgquup54j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnQ0YzWGRrOU4reGozTVhU
            YTFkaUhvR2VFUjFNRmhQRFRaRDM3bUJWajE4Cm4vaHZicGlYeVMvQjRuY0dFMExs
            R0hBM2NSRWNFdllHWFlXUnBDUXdEQ3cKLS0tIDArNzFiUGg5cDZUUldrTkhTN3M4
            T2x1alpzbW9YK1cxK2crcHZFRitMZU0KwJYtq7/PGgkczy+hSnQV+ZGzP1XT//fr
            IQcqtflAIVe+wA6x/60Gz3penbs3ikE2AhBO6OGkE/BSyTUR6IwAZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T19:29:14Z"
    mac: ENC[AES256_GCM,data:hbpSqteAFxTRDLRrmlyIqQi40sBuNqZBcZ1jZvhD1G7CVrodlHJJRwb1AvizXaEmrtp52OR1YJ580K5faXXAszPg6buxyzWxFch3tzMgAGXZ3EmcvoFBiM03UOAYOsJk+EHItAR6G7/QosTp1lRXhK3qpsVGwy+8n1AKJMGVV9A=,iv:c1sRm5Qoha/V2zp+gEr18dSrBV5PobOgtrrmcWiqtm0=,tag:1cNSjeFa7e3S26Ak7NDWUA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
