apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden
  namespace: home
  labels:
    app: vaultwarden
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaultwarden
  template:
    metadata:
      labels:
        app: vaultwarden
    spec:
      strategy:
        type: Recreate
      containers:
      - name: vaultwarden
        image: vaultwarden/server
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "100Mi"
            cpu: "100m"
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: vaultwarden-config
                key: DATABASE_URL
          - name: ADMIN_TOKEN
            valueFrom:
              secretKeyRef:
                name: vaultwarden-config
                key: ADMIN_TOKEN
        ports:
          - name: http
            containerPort: 80
        volumeMounts:
          - mountPath: /data/
            name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: vaultwarden