apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: vaultwarden
spec:
  image: vaultwarden/server
  interval: 5m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: vaultwarden
spec:
  imageRepositoryRef:
    name: vaultwarden
  policy:
    semver:
      range: ">=0.0.0"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden
  labels:
    app: vaultwarden
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaultwarden
  template:
    metadata:
      labels:
        app: vaultwarden
    spec:
      strategy:
        type: Recreate
      containers:
      - name: vaultwarden
        image: vaultwarden/server:1.35.2 # {"$imagepolicy": "vaultwarden"}
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "100Mi"
            cpu: "100m"
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: postgres-vaultwarden-config
              key: DATABASE_URL
        - name: ADMIN_TOKEN
          valueFrom:
            secretKeyRef:
              name: postgres-vaultwarden-config
              key: ADMIN_TOKEN
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
        - mountPath: /data/
          name: data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: vaultwarden