apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: cloudflared
  namespace: flux-system
spec:
  image: cloudflare/cloudflared
  interval: 5m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: cloudflared
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: cloudflared
  policy:
    semver:
      range: ">=0.0.0"
