apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: home-assistant
  namespace: flux-system
spec:
  image: ghcr.io/home-assistant/home-assistant
  interval: 5m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: home-assistant
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: home-assistant
  policy:
    semver:
      range: ">=0.0.0"
