apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: immich-ml
  namespace: flux-system
spec:
  image: ghcr.io/immich-app/immich-machine-learning
  interval: 5m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: immich-ml
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: immich-ml
  policy:
    semver:
      range: 2.x.x
