apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: minecraft
  namespace: flux-system
spec:
  image: itzg/minecraft-server
  interval: 5m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: minecraft
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: minecraft
  policy:
    semver:
      range: ">=0.0.0"
