apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: mosquitto
  namespace: flux-system
spec:
  image: eclipse-mosquitto
  interval: 5m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: mosquitto
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: mosquitto
  policy:
    semver:
      range: ">=0.0.0"
