apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: ollama
  namespace: flux-system
spec:
  image: ollama/ollama
  interval: 5m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: ollama
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: ollama
  filterTags:
    # Only allow plain semver tags like 0.15.4 (exclude -rc*, -rocm, latest, etc)
    pattern: '^[0-9]+[.][0-9]+[.][0-9]+$'
  policy:
    semver:
      range: ">=0.0.0"
