apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: open-webui
  namespace: flux-system
spec:
  image: ghcr.io/open-webui/open-webui
  interval: 5m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: open-webui
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: open-webui
  filterTags:
    # Prefer versioned tags, avoid ':main' and other non-semver tags.
    # NOTE: Upstream publishes both 'vX.Y.Z' and 'X.Y.Z'. If we match both,
    # Flux may flip-flop between tags that parse to the same SemVer.
    pattern: '^[0-9]+[.][0-9]+[.][0-9]+$'
  policy:
    semver:
      range: ">=0.0.0"
