apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: technitium
  namespace: flux-system
spec:
  image: technitium/dns-server
  interval: 5m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: technitium
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: technitium
  policy:
    semver:
      range: ">=0.0.0"
