apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llama-cpp-models
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: rook-cephfs

