apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft
spec:
  template:
    spec:
      containers:
      - name: minecraft
        envFrom:
        - secretRef:
            name: minecraft-config
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
        - ReadWriteOnce
        storageClassName: rook-ceph-block
        resources:
          requests:
            storage: 20Gi
        