apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: llmcord
spec:
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: rook-cephfs
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
