apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: sspti
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alliance-auth
  namespace: sspti
  labels:
    app: alliance-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alliance-auth
  template:
    metadata:
      labels:
        app: alliance-auth
    spec:
      containers:
      - name: alliance-auth
        image: mrakaki/dev-containers:sspti-auth-0.0.1
        command: ["/auth.sh"]
        ports:
          - name: http
            containerPort: 80
        resources:
          requests:
            memory: "256Mi"
            cpu: "300m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
          - mountPath: /app
            name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alliance-beat
  namespace: sspti
  labels:
    app: alliance-beat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alliance-beat
  template:
    metadata:
      labels:
        app: alliance-beat
    spec:
      containers:
      - name: alliance-beat
        image: mrakaki/dev-containers:sspti-auth-0.0.1
        command: ["celery", "-A", "myauth", "beat"]
        resources:
          requests:
            memory: "256Mi"
            cpu: "300m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
          - mountPath: /app
            name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alliance-worker
  namespace: sspti
  labels:
    app: alliance-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alliance-worker
  template:
    metadata:
      labels:
        app: alliance-worker
    spec:
      containers:
      - name: alliance-worker
        image: mrakaki/dev-containers:sspti-auth-0.0.1
        command: ["/worker.sh"]
        resources:
          requests:
            memory: "256Mi"
            cpu: "300m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
          - mountPath: /app
            name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
---
apiVersion: v1
kind: Service
metadata:
  name: alliance-auth
  namespace: sspti
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: alliance-auth