apiVersion: v1
kind: Secret
metadata:
    name: immich-redis-config
type: Opaque
stringData:
    host: ENC[AES256_GCM,data:B5XbsBENYSDfQOqAf+URWwi4seea6gvvh4cDcy0rktI1,iv:Elqseyj5PLNj3E2iMmUTqn3heaIyuuQzhHRcAB4a6HU=,tag:heMFHhYCSXIlA7EYov+ouw==,type:str]
    port: ENC[AES256_GCM,data:viVa+w==,iv:16e+7lZ1JgSxiJ8fja1ysczGhvKWQwDESW8i308pw2g=,tag:hONqqXclMTA8UkWKUu/OUw==,type:str]
sops:
    age:
        - recipient: age1fqgnfywtrv0v0v05xph328e90fk63vwsmz3qhra8zljdfsqn3fgquup54j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLU3dZajd6Z1I5bG5NelZv
            OE5LeTZWMnpJV1NiNUdDYXVvaUcrNGxaV2lFCk5lWTBCVGhzL0Q2T0ZDV2o3cGV1
            eTBabVloditOQ1hsclptdkZOb0Z5S2sKLS0tIFJFMXZJNGNseFE2NWdWMDAramU1
            c3hyZVBUS0pMUVBwWmFsTHJ1R2VTZWcKWuA958n0iEIknv2eAoy7YSUp99I38hFj
            ggbrvioJ8jXWL7tkY94AiOcrYgmEGPbHinBp7kkOcpuOS+RvvoYQgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-12T21:06:51Z"
    mac: ENC[AES256_GCM,data:y5WwfwgCfm9JNTGnhYOZfvVmbiRDG5lTvZ0olK+ExjfFj2/9m4Aj+uNpT7AMshC0bm1C7HKyrcVnqnvE1S3MZkAaT+h+q6v0QV/cR7Ozd1aM5HA7LFv+H9MX65SXbahiKIDwziKXjsFYwy/3tMkeYikiKIMp6nOYmZml8CC95Ls=,iv:qcOcEpWKjdN781dSe65vaUZz+n/wpJU4MZhOsr/bVqc=,tag:O/hDLiUYo2jsbjGRaSkhug==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
