apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
resources:
  - namespace.yaml
  - immich-postgres-config.yaml
  - immich-redis-config.yaml
  
  - ../../../apps/frigate 
  - ../../../apps/mosquitto
  - ../../../apps/zigbee2mqtt
  - ../../../apps/immich
  - ../../../apps/esphome
  - ../../../apps/homeassistant

patches:
  - path: patches/frigate.yaml
  - path: patches/mosquitto.yaml
  - path: patches/zigbee2mqtt.yaml
  - path: patches/immich.yaml
  - path: patches/esphome.yaml
  - path: patches/homeassistant.yaml
