apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
resources:
  - namespace.yaml
  - immich-postgres-config.yaml
  - immich-redis-config.yaml
  
  - ../../../apps/frigate 
  - ../../../apps/immich
  
patches:
  - path: patches/frigate.yaml
  - path: patches/immich.yaml
  