apiVersion: v1
kind: Secret
metadata:
    name: postgres-config
type: Opaque
stringData:
    host: ENC[AES256_GCM,data:DExDqQwAcjg1DqC9y+CjQCi+rL0qn6qOBlA0w8cfcdNl6y3E,iv:rhbtbLnmu+qNMlD8/LRROPd2bAysVID8knhZptzSBTs=,tag:UIiEiJKRWUHDh+3cwIpp/Q==,type:str]
    port: ENC[AES256_GCM,data:L9ChOA==,iv:RX+b5Sxm95IvRjVpKgY2p/hPbKNPZjO6CEPaT0JSUMo=,tag:K/7ARYCS3x7eZl80EUnc/w==,type:str]
    user: ENC[AES256_GCM,data:maM7K5Oa,iv:2OJ23Lpfm13S3UkqhI8TmkJr0mXJEEJVDWi8erRg4zE=,tag:iUBlswEicSxz+hy8pzL1gg==,type:str]
    password: ENC[AES256_GCM,data:uCtVW0jg,iv:vpPebi9Bkl/cDAHyNL5PVxvNrCW9UMUlzxtNvOCYU5k=,tag:9BWCqBQ8kNkJ/oCmdBtxUQ==,type:str]
sops:
    age:
        - recipient: age1gfg2cjnueyul65k0sdd3x85t2n6tlnspmfe7g87xzjt6f86y2fas63kt3x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6cUZDVDZiMGZiSlNOdjkr
            bjVramZkaHFrMVdzVjVwVisvS1kvYzViRUFnCm5MeXFKajYwUVR4K0JmRDh6UVVZ
            R1BqV3FLYjZJWXJ6djFTZlNRRlN3UlEKLS0tIFRObDVkbHBGOVV2c1ByaHdVeXpO
            L0pKTUFkcUhqcU5BRHQ2UGVtcHR5UGsKiA9wPRMz0igHBgYZN8XfPr/qIWzCe2is
            08kbQ371+xAGNr6/9ZTE6kaP+68WFjakR9L3m86Y86XFE6spuQE6FA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-13T00:30:03Z"
    mac: ENC[AES256_GCM,data:dLKiJPbKnTT7BreC2wLV2tc3j9+xMTgGPiqtESXLbGXuwujTNCR6aE2HGCqsnzqnhgPRuuSBLPzJ/yvwfOOl+o2yGl2cQyCLZ6sOACIOyB065sqFWCr58J3H1dygEEFkWe70eYvRImnNer/zQW6axMi+4Vb/c7Xc4N6RVqNNLUM=,iv:WlYkHCS0LcKDTlJCZmiBZ+3XGKksCV/hk/e9bVArrYo=,tag:MuKph7BkoXRhNV+TUjo1fA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
