apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mariadb
        image: mariadb:12.1.2
        env:
          - name: MARIADB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-config
                key: root-password
        ports:
        - containerPort: 3306
          name: mariadb
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql/
        - name: mariadb-config
          mountPath: /etc/mysql/mariadb.conf.d
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        startupProbe:
          exec:
            command: ["sh", "-c", "mariadb-admin ping --silent -h 127.0.0.1 -uroot -p$MARIADB_ROOT_PASSWORD"]
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 60
        readinessProbe:
          exec:
            command: ["sh", "-c", "mariadb-admin ping --silent -h 127.0.0.1 -uroot -p$MARIADB_ROOT_PASSWORD"]
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 10
        resources:
          requests:
            cpu: 2000m
            memory: 6Gi
      volumes:
      - name: mariadb-config
        configMap:
          name: mysql-cnf
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 50Gi