apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: immich
spec:
  image: ghcr.io/immich-app/immich-server
  interval: 5m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: immich
spec:
  imageRepositoryRef:
    name: immich
  policy:
    semver:
      range: 2.x.x
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: immich
spec:
  selector:
    matchLabels:
      app: immich
  serviceName: immich
  replicas: 1
  template:
    metadata:
      labels:
        app: immich
    spec:
      terminationGracePeriodSeconds: 10
      updateStrategy:
        type: RollingUpdate
      containers:
      - name: immich
        image: ghcr.io/immich-app/immich-server:v2.4.1 # {"$imagepolicy": "immich"}
        env:
        - name: TZ
          value: UTC
        - name: DB_HOSTNAME
          valueFrom:
            secretKeyRef:
              name: immich-postgres-config
              key: host
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: immich-postgres-config
              key: port
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: immich-postgres-config
              key: user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: immich-postgres-config
              key: password
        - name: DB_DATABASE_NAME
          value: immich
        - name: IMMICH_PORT
          value: "2283"
        - name: REDIS_HOSTNAME
          valueFrom:
            secretKeyRef:
              name: immich-redis-config
              key: host
        - name: REDIS_PORT
          valueFrom:
            secretKeyRef:
              name: immich-redis-config
              key: port
        - name: MACHINE_LEARNING_PORT
          value: "3003"
        - name: MACHINE_LEARNING_HOST
          value: immich-machine-learning
        ports:
        - name: http
          containerPort: 2283
        volumeMounts:
        - mountPath: /usr/src/app/upload
          name: data
        - mountPath: /dev/dri
          name: dri
          readOnly: true
        resources:
          requests:
            cpu: 2
            memory: 8Gi
          limits:
            cpu: 2500m
            memory: 8Gi
      volumes:
      - name: dri
        hostPath:
          path: /dev/dri
          type: Directory
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1.5Ti