apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: immich
spec:
  selector:
    matchLabels:
      app: immich
  serviceName: immich
  replicas: 1
  template:
    metadata:
      labels:
        app: immich
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: immich
        image: ubuntu #ghcr.io/immich-app/immich-server:v1.132.3
        command: ["sleep", "3600"]
        env:
          - name: TZ
            value: UTC
          - name: DB_HOSTNAME
            value: postgres
          - name: DB_PORT
            value: "5432"
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: postgres-config
                key: user
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-config
                key: password
          - name: DB_DATABASE_NAME
            value: immich
          - name: IMMICH_PORT
            value: "2283"
          - name: REDIS_HOSTNAME
            value: "redis"
          - name: REDIS_PORT
            value: "6379"
          - name: MACHINE_LEARNING_PORT
            value: "3003"
          - name: MACHINE_LEARNING_HOST
            value: immich-ml
        ports:
          - name: http
            containerPort: 2283 
        volumeMounts:
          - mountPath: /usr/src/app/upload
            name: data
  volumeClaimTemplates:
  - metadata:
      name:  data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "longhorn"
      resources:
        requests:
          storage: 512Gi