apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-ai
  namespace: flux-system
spec:
  interval: 10m
  path: ./overlays/magi/ai
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: infra-configs
  decryption:
    provider: sops
    secretRef:
      name: sops-age
