apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-sspti
  namespace: flux-system
spec:
  interval: 10m
  path: ./overlays/magi/sspti
  prune: true
  wait: true

  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: app-databases
  decryption:
    provider: sops
    secretRef:
      name: sops-age
