apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- 00-infrastructure.yaml
- 01-configurations.yaml

- ns-databases.yaml
- ns-sspti.yaml
- ns-tunnels.yaml
- ns-mrakaki.yaml
- ns-home.yaml