apiVersion: v1
kind: Service
metadata:
  name: technitium-dns-headless
spec:
  clusterIP: None
  selector:
    app: technitium-dns
  ports:
  - name: dns-tcp
    port: 53
    protocol: TCP
  - name: dns-udp
    port: 53
    protocol: UDP
  - name: web
    port: 5380
    protocol: TCP
