apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: frigate
spec:
  volumeClaimTemplates:
  - metadata:
      name: config
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: rook-ceph-block
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: media
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: rook-ceph-block
      resources:
        requests:
          storage: 1Ti
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [{
            "name": "cctv-net",
            "namespace": "default",
            "ips": ["172.16.25.200/24"]
          }]
    spec:
       affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: feature.node.kubernetes.io/coral-tpu.installed
                  operator: In
                  values:
                    - "true"
