apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: homeassistant
spec:
  volumeClaimTemplates:
  - metadata:
      name: config
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: rook-ceph-block
      resources:
        requests:
          storage: 25Gi
  - metadata:
      name: media
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: rook-ceph-block
      resources:
        requests:
          storage: 50Gi
      
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: |
            [{
              "name": "home-net",
              "namespace": "default",
              "ips": ["172.16.15.201/24","fd7a:6e5b:beff:15::201/64"]
            },{
              "name": "iot-net",
              "namespace": "default",
              "ips": ["172.16.20.201/24"]
            }]