apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: immich-ml
spec:
  volumeClaimTemplates:
    - metadata:
        name: immich-models
      spec:
        storageClassName: rook-ceph-block
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
        
        
      
      