apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: immich
spec:
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: rook-ceph-block
        resources:
          requests:
            storage: 1.5Ti

          
      
      