apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: technitium-dns
spec:
  volumeClaimTemplates:
    - metadata:
        name: config
      spec:
        accessModes:
        - ReadWriteOnce
        storageClassName: rook-ceph-block
        resources:
          requests:
            storage: 1Gi
        
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [{
            "name": "home-net",
            "namespace": "default",
            "ips": ["172.16.15.204/24","fd7a:6e5b:beff:15::204/64"]
          }]