apiVersion: apps/v1
kind: Deployment
metadata:
  name: zigbee2mqtt
  namespace: home
  labels:
    app: zigbee2mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zigbee2mqtt
  template:
    metadata:
      labels:
        app: zigbee2mqtt
    spec:
      strategy:
        type: Recreate
      containers: 
      - name: zigbee2mqtt
        image: koenkk/zigbee2mqtt:2.3.0
        ports:
          - name: web
            containerPort: 8080
        resources:
          requests:
            memory: "100Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        volumeMounts:
          - mountPath: /app/data
            name: config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: zigbee2mqtt