apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: zigbee2mqtt
spec:
  image: koenkk/zigbee2mqtt
  interval: 5m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: zigbee2mqtt
spec:
  imageRepositoryRef:
    name: zigbee2mqtt
  policy:
    semver:
      range: ">=0.0.0"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zigbee2mqtt
  labels:
    app: zigbee2mqtt
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: zigbee2mqtt
  template:
    metadata:
      labels:
        app: zigbee2mqtt
    spec:
      containers:
      - name: zigbee2mqtt
        image: koenkk/zigbee2mqtt:2.7.2 # {"$imagepolicy": "home:zigbee2mqtt"}
        ports:
        - name: web
          containerPort: 8080
        resources:
          requests:
            memory: "100Mi"
            cpu: "50m"
          #limits:
          #  memory: "512Mi"
          #  cpu: "200m"
        volumeMounts:
        - mountPath: /app/data
          name: config
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: zigbee2mqtt