apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zigbee2mqtt
  namespace: home
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi