apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: home
data: 
  mosquitto.conf: |  
    persistence true
    persistence_location /mosquitto/data/
    log_dest stdout
    listener 1883
    listener 9090
    protocol websockets
    allow_anonymous true