apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: home
  labels:
    app: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [{
            "name": "iot-lan",
            "namespace": "kube-system"
          }]
      labels:
        app: mosquitto
    spec:
      strategy:
        type: Recreate
      containers:
      - name: mosquitto
        image: eclipse-mosquitto:latest
        ports:
          - name: mqtt
            containerPort: 1883
          - name: mqtt-ws
            containerPort: 8001
        volumeMounts:
          - name: config
            mountPath: /mosquitto/config
          - mountPath: /mosquitto
            name: data
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 50m
            memory: 64Mi
      volumes:
        - name: config
          configMap:
            name: mosquitto-config
            defaultMode: 420
        - name: data
          persistentVolumeClaim:
            claimName: mosquitto