
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: loki-stack
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 10m
  values:
    grafana:
      enabled: false
    prometheus:
      enabled: false
    loki:
      persistence:
        enabled: true
        storageClassName: longhorn-unsafe
        size: 5Gi