apiVersion: batch/v1
kind: Job
metadata:
  name: ollama-pull-coding-model
  labels:
    app: ollama
spec:
  backoffLimit: 6
  ttlSecondsAfterFinished: 86400
  template:
    metadata:
      labels:
        app: ollama
    spec:
      restartPolicy: OnFailure
      containers:
        - name: pull
          image: ollama/ollama:0.15.4 # {"$imagepolicy": "flux-system:ollama"}
          env:
            - name: OLLAMA_HOST
              value: http://ollama:11434
            - name: CODING_MODEL
              valueFrom:
                configMapKeyRef:
                  name: ollama-model
                  key: CODING_MODEL
          command:
            - /bin/sh
            - -c
            - |
              set -e
              echo "Waiting for Ollama API..."
              until ollama list >/dev/null 2>&1; do
                sleep 2
              done
              echo "Pulling model: ${CODING_MODEL}"
              ollama pull "${CODING_MODEL}"
              echo "Done"
