apiVersion: v1
kind: Namespace
metadata:
  name: nginx-ingress
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  interval: 5m0s
  url: oci://ghcr.io/nginx/charts/nginx-ingress
  ref:
    semver: "^2.1.0"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  chartRef:
    kind: OCIRepository
    name: nginx-ingress
    namespace: nginx-ingress
  interval: 10m
  values:
    controller:
      replicaCount: 2
      enableCustomResources: true
      enableCertManager: true
      service:
        loadBalancerIP: 10.1.1.1