apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant
  namespace: home
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
  namespace: home
  labels:
    app: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      containers:
      - name: homeassistant
        image: ghcr.io/home-assistant/home-assistant:2025.5.2
        ports:
          - name: http
            containerPort: 8123
        volumeMounts:
          - mountPath: /config
            name: config
        resources:
          requests:
            cpu: 232m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 768Mi
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: homeassistant
---
apiVersion: v1
kind: Service
metadata:
  name: homeassistant
  namespace: home
spec:
  type: ClusterIP
  ports:
  - port: 8123
    name: http
  selector:
    app: homeassistant
