apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: home
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    name: postgres
  type: ClusterIP
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: home
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: postgres
        image: tensorchord/pgvecto-rs:pg16-v0.2.1
        args: ["-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
        env:
          # fix issue with db not starting because folder is not empty
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
          - name: POSTGRES_PASSWORD
            valueFrom: 
              secretKeyRef:
                name: postgres-config
                key: password
          - name: POSTGRES_USER
            valueFrom: 
              secretKeyRef:
                name: postgres-config
                key: user
          - name: POSTGRES_INITDB_ARGS
            value: '--data-checksums'
        ports:
        - containerPort: 5432
          name: "postgres"
        volumeMounts:
        - name: postgres
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name:  postgres
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "longhorn"
      resources:
        requests:
          storage: 10Gi