
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: postgres
        image: ghcr.io/immich-app/postgres:16-vectorchord0.3.0-pgvectors0.3.0
        env:
          # fix issue with db not starting because folder is not empty
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
          - name: POSTGRES_PASSWORD
            valueFrom: 
              secretKeyRef:
                name: postgres-config
                key: password
          - name: POSTGRES_USER
            valueFrom: 
              secretKeyRef:
                name: postgres-config
                key: user
          - name: POSTGRES_INITDB_ARGS
            value: '--data-checksums'
        resources:
          requests:
            cpu: 2000m
            memory: 6Gi
        ports:
        - containerPort: 5432
          name: "postgres"
        volumeMounts:
        - name: postgres
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 128Gi