apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: npm-wg
spec:
  template:
    metadata:
      labels:
        app: npm-wg
      annotations:
        k8s.v1.cni.cncf.io/networks: |
            [{
              "name": "home-net",
              "namespace": "default",
              "ips": ["172.16.15.200/24","fd7a:6e5b:beff:15::200/64"]
            }]

  volumeClaimTemplates:
    - metadata:
        name: npm-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: rook-ceph-block
        resources:
          requests:
            storage: 10Gi
    - metadata:
        name: npm-ssl
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: rook-ceph-block
        resources:
          requests:
            storage: 2Gi

          
      
      