apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: npm-wg
spec:
  template:
    metadata:
      labels:
        app: npm-wg
      annotations:
        k8s.v1.cni.cncf.io/networks: |
            [{
              "name": "home-net",
              "namespace": "default",
              "mac": "c6:5e:a4:8a:6b:5b",
              "ips": ["172.16.15.203/24"]
            }]
    spec:
      initContainers:
      - name: route-init
        image: wbitt/network-multitool:latest
        securityContext:
          privileged: true
        command:
        - /bin/sh
        - -c
        - |
          set -eux
          ip route add 172.16.15.0/24 dev net1 table 100
          ip route add default via 172.16.15.1 dev net1 table 100
          ip rule add from 172.16.15.203 lookup 100
  volumeClaimTemplates:
    - metadata:
        name: npm-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: rook-ceph-block
        resources:
          requests:
            storage: 10Gi
    - metadata:
        name: npm-ssl
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: rook-ceph-block
        resources:
          requests:
            storage: 2Gi

          
      
      