apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: lab-open-webui
  namespace: lab
spec:
  dependsOn:
    - name: infra-monitoring
      namespace: flux-system
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  targetNamespace: lab
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./apps/open-webui
  prune: true