apiVersion: v1
kind: Secret
metadata:
    name: npm-wg-secret
type: Opaque
stringData:
    wg0.conf: ENC[AES256_GCM,data:vQECIS7TysMEXin8xqN0vIIbSQXCwRCR1Gp/FzV7i4Qc3Jgg+8GkVhjdabeJXFAaEbjUuk8ayMorMNnqFIgiu/e1dl5bYE43ReSOWFczAr4fo30pqEI02xkLxQha7t0MKfbVWiyMOcdsrpVJwTWLY5Ys+uqOLIt1yh/KsHxCNqwJ/K2yzgCdpHbuRbvFeP7zDNFkuX7FbwgIBrcpLg1naiMu1FD9brHmkUdf7yBNlpFWO54ZlWM1SsohYapwkCLGM3kVBw0TG8pp1Z+zKL6l8M8kZDkiCltmkMTqbICtQiRdYMv5wpyVthOEr3G3K+Pz5kDP5bDacbBZEnCzh6OJ3TULHwFGzmw=,iv:hacPD/lopPqLv6vjHpwBiiKDcJPDHuGr395nDECy+h4=,tag:l5nIEOdBYsi19xuZ7PFXaw==,type:str]
    db-host: ENC[AES256_GCM,data:8MGNp4A/OT4yJetmj7NY1eOuYh2ZhBifsp/9/BWvo0ut,iv:r7U9aDSgX+rRTG5Q8CQrMRHzEZfFe+rF2Z1pNC2HFj8=,tag:esel39Bbwn6fnoFQhSpaKQ==,type:str]
    db-port: ENC[AES256_GCM,data:zRGuXQ==,iv:gANZCww9u42Dd6YqjdaZAiNmIBN16BigYzT4ngaADNI=,tag:43gNYYjNzmhdOj3OOUGssQ==,type:str]
    db-name: ENC[AES256_GCM,data:firufO5hxc+NFh3F1A==,iv:MLQGAy3D5UM71fyNZu0IqJ+G5GM7TdP7drGSHOsG2Q4=,tag:GaH1/I3hZvh1m3h/v94tDA==,type:str]
    db-user: ENC[AES256_GCM,data:6CvFzKS3rcce8mH6Fg==,iv:lL0mb3VCgsMNuVk92X3ut43nR68gbGoP/RdlGG4WUNc=,tag:IisfNG/0hntK6JL+G0R5ug==,type:str]
    db-password: ENC[AES256_GCM,data:dEZHO0ppFmHcSsgRQtoF,iv:8MB/iMN4/rRHFCCpTG1M9G4CaQGn0u1iNvA+RQrTI6Y=,tag:FU3RvnVCxJ5NVguBc+ZdXA==,type:str]
sops:
    age:
        - recipient: age1gfg2cjnueyul65k0sdd3x85t2n6tlnspmfe7g87xzjt6f86y2fas63kt3x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Vlc0KzAyeDBoZXRpZ3RW
            SHFzRWlQNEdHMlVLSzVRRnlxc1RyNEtEZmljCjRDMkEyeWZFMW1iR1ZsaU9qVnIx
            YWdhMUlFKytDUDRJbGViTWdpSEg2SEkKLS0tIE1tZlZPUVhBRk5KSGVZNVh3TDl6
            YnVmWkpGa2syQVhOcVpHZ09jRVZmMjgKfxkFQY62tOuzlr1g3KFWVMKFJka3Ns/a
            23FjRO0luLiqNxqKaaU5D2ooddPiVrcvH6eEQNwlDIgl7RibyMpnOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-21T20:52:51Z"
    mac: ENC[AES256_GCM,data:0zBrMqRe1ZXz+8PYDpNEV6Gv17ZhI/NUIpzf53Hx22PQ5SiM7mZ56bsibVBGBTnXvPJPa1WW7XinW338nn3wu3xEazL6p1kV8cPDHSFbtcgYvLtYx4NqDwecBz08ziLmZ09huP7AD0EzYWaFgL7ZXwJ0csim1E+b6rYHcYj+PfM=,iv:7rBrbKG70PSaLxMJD5C5KJO35LLD/m60pHTHBB8tELY=,tag:bz6YXYqjBy/eFZNsYzD9qg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
