apiVersion: v1
kind: Secret
metadata:
    name: pangolin-env
type: Opaque
stringData:
    NEWT_ENDPOINT0: ENC[AES256_GCM,data:EBmY9gPHqgPeidrF9wANhAxX2X6kq6M=,iv:NFBjJN2HCyL2UQd9wRUBVa/oxPWRv8/9f5fEVXaWVY4=,tag:awSF94KndsqDqtP2I38oCg==,type:str]
    NEWT_ID0: ENC[AES256_GCM,data:6JsbLkCcYHRsXgBGb6Fx,iv:ddYZ55sUnD/FNBQLGsTa91B8OG5hCok1pHWiJ5zbcJ8=,tag:/gEVt0Ez4IW4g9c134lCmA==,type:str]
    NEWT_SECRET0: ENC[AES256_GCM,data:LNc5MovkgoDUCfD/Ao1M6Ae0ALSjvPLst8gbb4KTa58NZOeS16HDU0O7ZzfY6zs+,iv:Fs//bpr499s498XmFYrdvzW9chhCMgejx0JXv8F/lIE=,tag:UQpkk1PDJ+j5tZnTQfXRtA==,type:str]
    NEWT_ENDPOINT1: ENC[AES256_GCM,data:pYXq7rhhE7TGmsBJR8HStv4CifIKUzDG,iv:x5aifgnis+7sna0Myg5JRMhC9fIzRyuQQ3ZsdFoCX2U=,tag:1n0wUUSNgPY8cQrUhZCkHw==,type:str]
    NEWT_ID1: ENC[AES256_GCM,data:Thio+XWwHqRowjRcoU0+,iv:ftICiLNPDAwhbsOxIhadN9ZDhZmtWkRtkMtMOmKFuCI=,tag:WRgsVXADE/Xfi0ce7T3W0w==,type:str]
    NEWT_SECRET1: ENC[AES256_GCM,data:caHjEjyw4k3j9gKng2klXmnYjPLzuiqqJqqIKszhGulSneCVVOoiPmRB3U/cO0ta,iv:i6tVQaKiHqVRV25MGuUnP69NwsQGU00uC47USd18eys=,tag:/nurfQA2WmgmB6vi5f3i/w==,type:str]
sops:
    age:
        - recipient: age1gfg2cjnueyul65k0sdd3x85t2n6tlnspmfe7g87xzjt6f86y2fas63kt3x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHVnhuQ2pMMGpER3U4cDNQ
            Yk5hN2MwRVFicnJualhTRVRHZ1pMWFZDRXprCit0Sy9sWVJMdzlTR0Y4VEdnaW5u
            emFYTTRTd1dFT0g5bnRtb2RYcDgwMlUKLS0tIGlLUXB0dWszZmR5bGdRU00vUWZP
            Q213RVRKL2lkVThUWTJlNTVFOTc4MkkKmhQ7GYFqTUY4lFI8UVwGnFwTS0Db6Nco
            nChhhULRNia2qSEDlDsuIhgrVkzwdj/9QlCxfUd1tUZUzAeXC8AMMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-13T00:01:00Z"
    mac: ENC[AES256_GCM,data:eur6MeGtSKYR1alZmWcoBxfTBenpRcTdoA0WBdXhuw7zohk+KXRCv693MGjM3EleDimvm6HQmNDxc2UGg7BnsmCyndQp7CEXO/wQVpRtte7bgaF8puTbFychlcuL2UKMFFu1bFjFMab9kPa7tLCgao2jOl2A8kLGJ6u0s0Rz9Uw=,iv:s95Xmy3E9iumFCne22Dhp+R8dWKUvCP9NiV6N/mDJ9I=,tag:g/oW5lD1te2Zbq329ssmZA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
