apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns01-cloudflare
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: me@vbalex.com 
    privateKeySecretRef:
      name: cloudflare-api-token-secret-tls
    solvers:
    - dns01:
        cloudflare:
          email: vb.alexr@gmail.com
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-key