apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: metallb-advertisment
  namespace: metallb-system
spec:
  ipAddressPools:
  - metallb-pool 
  aggregationLength: 32
  localPref: 100
  communities:
  - 65535:65282
---
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: bgppeer-router-10-1-0-2
  namespace: metallb-system
spec:
  myASN: 64500
  peerASN: 64501
  peerAddress: 10.1.0.2
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metallb-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.1.0.128/25
  - 10.1.1.0/24
  - 10.1.2.0/24