apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: coral-pci-rule
spec:
  rules:
    - name: "nfd coral pci tpu rule"
      labels:
        "coral-tpu.installed": "true"
      matchFeatures:
        - feature: pci.device
          matchExpressions:
            device:
              op: In
              value: ["089a"]