apiVersion: apps/v1
kind: Deployment
metadata:
  name: pangolin
  labels:
    app: pangolin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pangolin
  template:
    metadata:
      labels:
        app: pangolin
    spec:
      containers:
        - name: pangolin
          image: fosrl/newt
          imagePullPolicy: IfNotPresent
          env:
            - name: PANGOLIN_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: pangolin-env
                  key: NEWT_ENDPOINT
            - name: NEWT_ID
              valueFrom:
                secretKeyRef:
                  name: pangolin-env
                  key: NEWT_ID
            - name: NEWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: pangolin-env
                  key: NEWT_SECRET
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          securityContext:
            readOnlyRootFilesystem: true
        