apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: frigate
spec:
  interval: 10m
  chart:
    spec:
      chart: frigate 
      sourceRef:
        kind: HelmRepository
        name: blakeblackshear
      interval: 10m
  valuesFrom:
    - kind: Secret
      name: frigate-values
      valuesKey: values.yaml
      optional: false