apiVersion: v1
kind: Service
metadata:
  name: homeassistant
  namespace: home
spec:
  type: LoadBalancer
  loadBalancerIP: 10.1.0.201
  ports:
  - port: 8123
    name: http
  selector:
    app: homeassistant