apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: homeassistant
  labels:
    app: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  serviceName: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      containers:
      - name: homeassistant
        image: ghcr.io/home-assistant/home-assistant:2026.2.2 # {"$imagepolicy": "flux-system:home-assistant"}
        ports:
        - name: http
          containerPort: 8123
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /media
          name: media
        resources:
          requests:
            cpu: 232m
            memory: 768Mi
          limits:
            cpu: 500m
            memory: 1G
  volumeClaimTemplates:
  - metadata:
      name: config
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 25Gi
  - metadata:
      name: media
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 50Gi
