apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant
  namespace: home
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi