apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 25Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi