apiVersion: v1
kind: Secret
metadata:
    name: postgres-config
    labels:
        app: postgres
type: Opaque
stringData:
    user: ENC[AES256_GCM,data:bs5koIctNww=,iv:YHioFmDJzKz3BM8ZmcZogKDPrTSb+v9zO16Uhqly+Ag=,tag:GnP+ggz3e8B2cdfNTNOLRw==,type:str]
    password: ENC[AES256_GCM,data:kq8KNp0XieZUerVqENZP,iv:PMY9ObWHC6LTVJ0UPdjSsd/SeebIaB+u+2Vj0P7sCVI=,tag:aLuIpz0ydiD9SFqs5+kdHQ==,type:str]
sops:
    age:
        - recipient: age1gfg2cjnueyul65k0sdd3x85t2n6tlnspmfe7g87xzjt6f86y2fas63kt3x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArM2s5Mkh6YklHNjNlNGNH
            V3VjaHk5YzFSWFRPM0R5WlFMVWMzRmZFYkJrCmNPSExrUlNhS2M0S21wUW5LbVE3
            R1VxRDBFS0NZRUY1Q2JCUlBZb2MyYm8KLS0tIGtMaW9YNWgrSnBzUFlTaDVCNDE0
            dG03RDJhVFZBTW9jMGptWHJySXNNa00KElvXaY5KW13moyeOuyPSIjFgERirJfV0
            9iCeSLtdps9VQKtNAZ72N6EQ9Vkq1Nw+6B2DurDYB0R/9NSlJFlYSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-12T04:07:00Z"
    mac: ENC[AES256_GCM,data:zjMKuKpEh+wXJ2fJR/KPaM8pJWh/n7jk/pOqy/HMRrejqMxBBG0fbmN8a3oC3CGbgeib20D7RWgev3FYGdRfxCw0vBHGOtNWJ6ex8yFgGJDTZSkUAV4noMI9uTuKbGQ0qH3xEXW0Df44ZsojdmPkXtTEja26f0v4tu7YYGl1Fyg=,iv:PCmKvBBmYl+8Cj0cFryqjFFMNwdS0pXN+MgHZdY04KM=,tag:lxyAjfRkFAnO8nxYt28VXg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
