apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llama-cpp-models
  labels:
    app: llama-cpp
spec:
  accessModes:
    # Must be backed by a RWX-capable StorageClass (e.g., NFS, CephFS).
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
