apiVersion: v1
kind: Service
metadata:
  name: llama-cpp-headless
  labels:
    app: llama-cpp
spec:
  clusterIP: None
  selector:
    app: llama-cpp
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
