apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: frigate
spec:
  template:
    spec:
       affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: feature.node.kubernetes.io/coral-tpu.installed
                  operator: In
                  values:
                    - "true"
  volumeClaimTemplates:
  - metadata:
      name: config
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: media
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 256Gi
---
apiVersion: v1
kind: Service
metadata:
  name: frigate
  labels:
    lb-pool: private
spec:
  type: LoadBalancer
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
    - IPv4
    - IPv6