apiVersion: v1
kind: Secret
metadata:
    name: skynet-env-secret
stringData:
    DISCORD_TOKEN: ENC[AES256_GCM,data:3im/rEVsiIwlG4jdU/ll1qJyNoMRh/DEQvWxIEDKhZNOSlDP6Uloy6JJ8QmL8ZbaDmbC6mOCjC38nWL47tDg2HAZ1tjRFi12,iv:I7LnCBs+ge/08ECkA99KPXGCTFifM3/iz89uf/OWf9k=,tag:f/qv+6ftDwwH0yjs0371jA==,type:str]
    CLIENT_ID: ENC[AES256_GCM,data:pmiYZWCkr5oYMgSFqUVGMJacYQ==,iv:7fev5YQD4eZA2k1zd+gyweHnTMwqpv0hfxNrYErlU+Y=,tag:Z71UaeNhmF6+I7A+9ORXMw==,type:str]
    GUILD_ID: ""
    ALLOWED_CHANNEL_IDS: ""
    LLAMA_BASE_URL: ENC[AES256_GCM,data:5vRcVT1VyVzNbZIvIZzN0Kwf+Muudr6PBI4yX2PpCg8mEfpmlw==,iv:AwrjMBxpfebqvEZHhC3hozAKdvwK/l3wrVqlMgHq4FI=,tag:gIVBwYjXBhv9LDGq9qKR/w==,type:str]
    LLAMA_API_KEY: ""
    LLAMA_MODEL: ENC[AES256_GCM,data:gQs8yAhrYH70LIqnAYcPhLefc7gp942wZWWFliLrOQ==,iv:FcYMz7w5jWf8P8TJgyjQunv416liB3cvUFgi2StmfJU=,tag:IJuKjH4M7ORffclt6QTkmw==,type:str]
    LLAMA_TEMPERATURE: ENC[AES256_GCM,data:9QNwzg==,iv:2I2CwetL5UBqQuWEnqDMVT59+p8eD1n99ZYPqzqZvVU=,tag:NCIAMGQ2PcfqhDfeEvTRgg==,type:str]
    LLAMA_MAX_TOKENS: ENC[AES256_GCM,data:0RWo,iv:INYX1YT4iOT/u1P6gzl2Xhw6Kk1cT62/NLZ1Ol8Wa5M=,tag:BpXarhQ7BrT5ODpTiodHRg==,type:str]
    KNOWLEDGE_DIR: ENC[AES256_GCM,data:kOYWCr8qk8J/,iv:+XDgPXSXpOvLT36oLOv0vYTdwW3J0gRR3dGk7HC4lVQ=,tag:bAqzSz5Yf/grUurNCLHiZg==,type:str]
    KNOWLEDGE_TOP_K: ENC[AES256_GCM,data:Qg==,iv:NhabagC6Ax+J38W6TCG+NNubRbXycS+SAo0yuoX8jNg=,tag:VmdBEocZUcngFJVJvFoJzw==,type:str]
    JANICE_API_KEY: ENC[AES256_GCM,data:PyeZBwADGxXEbRUt3Cbs1gQrwsxgINoA+bXc7moth7I=,iv:isqUx33DBgTRmInw+MqaVL4clHoWOEnl3NeFJNDMEUQ=,tag:nNw9SmosYj/Zcaeo57PmCg==,type:str]
    LOG_LEVEL: ENC[AES256_GCM,data:CbAn8vw=,iv:7vh0KadMpNbjWgDU6hq1YMpTH6PVgmhdxy6r6HsD2DU=,tag:Q0eAzRNlkGdCDFNawB6TmA==,type:str]
sops:
    age:
        - recipient: age1gfg2cjnueyul65k0sdd3x85t2n6tlnspmfe7g87xzjt6f86y2fas63kt3x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6aUZ0Zmd5bndpOW5zeTdO
            VGJaU2JaVUoxbGdqRVdDVXF2d1BzTW10aEhrCjlPWm5qa1IxZFZRQWtENUFlaU5N
            UTgwWUo1eXV0akdlL2RKNEFkSTMwdE0KLS0tIENKREdlZVlud1d0bXpxMElvaGQw
            Smg4ZVJZTkM3Z0hMZW9vVFo1SVMzaE0KXoTEghIT3Rznx04mVpReeC2+ekwZ3wy6
            KWT+ee+HUJH2nBRgYsxCjGTO8Z7BFnCHnPeE3XNN7MRpUypMfTtLMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-20T05:52:11Z"
    mac: ENC[AES256_GCM,data:Vz1HLG/26XsZMYHBsqN322UKAGKq31CI+Bid3S9agz6ndrno9pdpRXSrDgDXqix0Gv/XawOdSg2NLgMdwGzeDDskzALomluDT8CbD9QAtOrppx1KzwkwcGuhD9Pe/odXwS1jEe1XECb8blP8JLXd26iKycYKMjZac3EDWccPzYA=,iv:+r+6/Ms7zESGWZKDKBT3y83tI7uQdP/Avcmdl80tEvA=,tag:i80Gs133xuBXw1B0fPtvHQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
