apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: esphome
  namespace: lab
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi