apiVersion: v1
kind: Service
metadata:
  name: mysql
  annotations:
    metallb.io/address-pool: prod-services
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
    - IPv4
    - IPv6
