apiVersion: v1
kind: Service
metadata:
  name: redis
  annotations:
    metallb.io/address-pool: prod-services
spec:
  type: ClusterIP
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
    - IPv4
    - IPv6
