apiVersion: v1
kind: Namespace
metadata:
  name: home
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: production-home
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-monitoring
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/home
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: home-immich
  namespace: home
spec:
  dependsOn:
    - name: infra-monitoring
      namespace: flux-system
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  targetNamespace: home
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./apps/immich
  prune: true
