apiVersion: v1
kind: Namespace
metadata:
  name: home
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: home-postgres
  namespace: home
spec:
  dependsOn:
    - name: infra-monitoring
      namespace: flux-system
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  targetNamespace: home
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./apps/postgres
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: home-redis
  namespace: home
spec:
  dependsOn:
    - name: infra-monitoring
      namespace: flux-system
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  targetNamespace: home
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./apps/redis
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: home-mosquitto
  namespace: home
spec:
  dependsOn:
    - name: infra-monitoring
      namespace: flux-system
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  targetNamespace: home
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./apps/mosquitto
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: home-zigbee2mqtt
  namespace: home
spec:
  dependsOn:
    - name: home-mosquitto
      namespace: home
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  targetNamespace: home
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./apps/zigbee2mqtt
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: home-assistant
  namespace: home
spec:
  dependsOn:
    - name: home-postgres
      namespace: home
    - name: home-mosquitto
      namespace: home
    - name: home-zigbee2mqtt
      namespace: home
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  targetNamespace: home
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./apps/homeassistant
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: home-immich
  namespace: home
spec:
  dependsOn:
    - name: home-postgres
      namespace: home
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  targetNamespace: home
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./apps/immich
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: home-frigate
  namespace: home
spec:
  dependsOn:
    - name: home-postgres
      namespace: home
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  targetNamespace: home
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./apps/frigate
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: home-vaultwarden
  namespace: home
spec:
  dependsOn:
    - name: home-postgres
      namespace: home
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  targetNamespace: home
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./apps/vaultwarden
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: home-plex
  namespace: home
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  targetNamespace: home
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./apps/plex
  prune: true