apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: redis
spec:
  image: redis
  interval: 5m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: redis
spec:
  imageRepositoryRef:
    name: redis
  policy:
    semver:
      range: ">=0.0.0"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:8.4.0 # {"$imagepolicy": "redis"}
          ports:
            - name: http
              containerPort: 6379
          resources:
            requests:
              memory: "1Gi"
              cpu: "1000m"
          livenessProbe:
            exec:
              command:
              - redis-cli
              - ping
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            exec:
              command:
              - redis-cli
              - ping
            initialDelaySeconds: 5
            periodSeconds: 5
          