apiVersion: v1
kind: Secret
metadata:
    name: mariadb-credentials
type: Opaque
stringData:
    root-password: ENC[AES256_GCM,data:3E+5jYJsaE4banZm,iv:j/FVHU5JNshbXeILWMcbXFjDtTXNQQeiqVUg1j9aU5c=,tag:XWxz8IQVtfm+tg1f91cD6g==,type:str]
sops:
    age:
        - recipient: age1fqgnfywtrv0v0v05xph328e90fk63vwsmz3qhra8zljdfsqn3fgquup54j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZb09mRU41YW5YV3RhZ0xP
            blhaWWphR2Q1MStBYmppNkswT0IyQVdPMWdZCnIzTllGNktDSmdZTWpaR1BwUUtK
            UmdCRHg1bDZzUmJxOVhpK24wT2IzTFEKLS0tIHdEMmx1SElrMWJGaXc5VVVvN1Rs
            ZkRXaWZkV2RmQnZaQkVUeDY1V2lKbXMK2T+EnHPSE7fzXVGHq2yZRASbjbC5e6V4
            Go2QoYWjDV02PVMhg6dE0q/RXTSAKF/C/yDHpqLHPm/8dCAA/2QZlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T18:37:26Z"
    mac: ENC[AES256_GCM,data:huRCXMr8lNVM3Y+p2GI6GWnKLRKtfBdtexVhFETYcPLwUH/++bh6UXM8YYOOBDowbc0Q6hKthOCJALjU4GH4LklWvtDZNxi40NvB6Nqxy0VG4Qp30kBs/7z0TnFNSfus0RYSabVemhVFHx8iPwHZ68ZNM54UkP8ppiqlz443n54=,iv:WWfcKPR8bmH/tNlNGj8cnFf7NybC4YX7sbXgp2efr4Q=,tag:AIjc1ERmf2H+RoGJNrURyQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
