apiVersion: v1
kind: Secret
metadata:
    name: postgres-credentials
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:pZJ5noH8Sf5tYQn9ccpvId9xqRj3+fDmXFodkhORvA==,iv:WkESOIgdOw08ldcmp41okcIn2PhQi7RyHduPBDJE51I=,tag:Vlpc88Ga/IDm3cpTlxmwgQ==,type:str]
    user: ENC[AES256_GCM,data:jfS7ZRkWzUo=,iv:cWBHjy1XaE7LnfgME5U84l9WbulRCqutVhMFSFuz+uo=,tag:GI8iugJdD/T6JtHRvSWTCw==,type:str]
sops:
    age:
        - recipient: age1fqgnfywtrv0v0v05xph328e90fk63vwsmz3qhra8zljdfsqn3fgquup54j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGQnBDMThqdUdiazNhSzZW
            RjR3UHA1R1NqWTFWbzVWQTNKQ3k0Y1dCcmhjCmJ3STlHWStSYmNVekgxMThTeTcx
            RC9aMEk0QVgyZ3ZadTNldENyNG9aVVkKLS0tIElyUlYvTVFuQUFRKzhXQmhZNXRn
            L2FKUXVLTkdpZ1BURlBUaU1EN0dTdEUKYEMYe9S1RaXDs1XNhQvpfrVHEE9+Ch07
            XZfP8kDMIigT1RMZ4eP36du7KJlEkQUkPbmSVyatD7zZTNThu19tTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T18:37:18Z"
    mac: ENC[AES256_GCM,data:p4gMAtUFDFLpQB8lJoPqW1KTLSbFbuxb96kK8s0Z83xYC7bPqRVGcKfz4PQhJ+GFIPojm3Zcg7kpZLH0fKRf34Qm2GyzihZ6lVdb21tuaZqYmCKaDfdCQyt54f4F2thst7y8nOx9/7aZgQVy6VIz+0zGKVd7EudKdA4mfSJngH4=,iv:1pbyOpPAvLfg1hUc6SyxsVCEsEFQV3BG1y5RKKZ7Nac=,tag:4QXRBaA4WbEOJuvKQPL5nA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
