apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft
  labels:
    app: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  serviceName: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
      - name: minecraft
        image: itzg/minecraft-server:2026.3.0 # {"$imagepolicy": "flux-system:minecraft"}
        tty: true
        stdin: true
        ports:
        - name: minecraft
          containerPort: 25565
          protocol: TCP
        env:
        - name: EULA
          value: "TRUE"
        volumeMounts:
        - mountPath: /data
          name: data
        resources:
          requests:
            cpu: 500m
            memory: 2Gi
          limits:
            cpu: 2000m
            memory: 4Gi
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
